### ISSUE TITLE
Remove PaxHeaders from distributed package

### ISSUE THREAD

**Issue by ayashjorden** [n1tr0g/golja-gnupg#18]
Hi @n1tr0g ,
I'm having an issue similar to [this](https://github.com/deadpoint/puppet-zypprepo/issues/11).

Can you please re-package and update the Forge?

Thank you,
Yarden

**Comment by n1tr0g** [comment]
hey tnx ... Interesting whenever I package the module I use puppet module command, but maybe was an older version. I will re-package it with the next release. tnx

**Comment by ayashjorden** [comment]
Awesome! :+1:

**Comment by rnelson0** [comment]
@n1tr0g Can you do a 0.0.z point release to fix this? It's filling logs pretty quickly. Thanks!

**Comment by n1tr0g** [comment]
sure ... will do it tonight ...

**Comment by n1tr0g** [comment]
done version 1.2.2 released

**Comment by rnelson0** [comment]
@n1tr0g Hrm, this still shows up with 1.2.2. I'm not sure what command you're using and what version of tar you have, but the problem persists. Perhaps a tar with different flags than puppet expects?
````
INFO     -> Deploying module /etc/puppetlabs/code/environments/hiera4/modules/gnupg
WARN     -> These files existed in the module's tar file, but are invalid filetypes and were not unpacked: ["PaxHeader/golja-gnupg-1.2.2", "golja-gnupg-1.2.2/PaxHeader/CHANGELOG", "golja-gnupg-1.2.2/PaxHeader/checksums.json", "golja-gnupg-1.2.2/PaxHeader/CONTRIBUTING.md", "golja-gnupg-1.2.2/PaxHeader/files", "golja-gnupg-1.2.2/PaxHeader/Gemfile", "golja-gnupg-1.2.2/PaxHeader/lib", "golja-gnupg-1.2.2/PaxHeader/LICENSE", "golja-gnupg-1.2.2/PaxHeader/manifests", "golja-gnupg-1.2.2/PaxHeader/metadata.json", "golja-gnupg-1.2.2/PaxHeader/Rakefile", "golja-gnupg-1.2.2/PaxHeader/README.md", "golja-gnupg-1.2.2/PaxHeader/spec", "golja-gnupg-1.2.2/PaxHeader/tests", "golja-gnupg-1.2.2/tests/PaxHeader/gnupg_key.pp", "golja-gnupg-1.2.2/tests/PaxHeader/init.pp", "golja-gnupg-1.2.2/spec/PaxHeader/acceptance", "golja-gnupg-1.2.2/spec/PaxHeader/classes", "golja-gnupg-1.2.2/spec/PaxHeader/fixtures", "golja-gnupg-1.2.2/spec/PaxHeader/spec.opts", "golja-gnupg-1.2.2/spec/PaxHeader/spec_helper.rb", "golja-gnupg-1.2.2/spec/PaxHeader/spec_helper_acceptance.rb", "golja-gnupg-1.2.2/spec/PaxHeader/spec_helper_system.rb", "golja-gnupg-1.2.2/spec/PaxHeader/system", "golja-gnupg-1.2.2/spec/PaxHeader/unit", "golja-gnupg-1.2.2/spec/unit/PaxHeader/puppet", "golja-gnupg-1.2.2/spec/unit/puppet/PaxHeader/type", "golja-gnupg-1.2.2/spec/unit/puppet/type/PaxHeader/gnupg_key_spec.rb", "golja-gnupg-1.2.2/spec/system/PaxHeader/gnupg_key_install_spec.rb", "golja-gnupg-1.2.2/spec/system/PaxHeader/install_spec.rb", "golja-gnupg-1.2.2/spec/fixtures/PaxHeader/manifests", "golja-gnupg-1.2.2/spec/fixtures/PaxHeader/modules", "golja-gnupg-1.2.2/spec/classes/PaxHeader/gnupg_init_spec.rb", "golja-gnupg-1.2.2/spec/acceptance/PaxHeader/class_spec.rb", "golja-gnupg-1.2.2/spec/acceptance/PaxHeader/gnupg_key_install_spec.rb", "golja-gnupg-1.2.2/spec/acceptance/PaxHeader/nodesets", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/centos-59-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/centos-64-x64-pe.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/centos-64-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/centos-65-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/debian-607-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/debian-70rc1-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/debian-73-i386.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/debian-73-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/default.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/ubuntu-server-10044-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/ubuntu-server-12042-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/ubuntu-server-1310-x64.yml", "golja-gnupg-1.2.2/spec/acceptance/nodesets/PaxHeader/ubuntu-server-1404-x64.yml", "golja-gnupg-1.2.2/manifests/PaxHeader/init.pp", "golja-gnupg-1.2.2/manifests/PaxHeader/install.pp", "golja-gnupg-1.2.2/manifests/PaxHeader/params.pp", "golja-gnupg-1.2.2/lib/PaxHeader/facter", "golja-gnupg-1.2.2/lib/PaxHeader/puppet", "golja-gnupg-1.2.2/lib/puppet/PaxHeader/provider", "golja-gnupg-1.2.2/lib/puppet/PaxHeader/type", "golja-gnupg-1.2.2/lib/puppet/type/PaxHeader/gnupg_key.rb", "golja-gnupg-1.2.2/lib/puppet/provider/PaxHeader/gnupg_key", "golja-gnupg-1.2.2/lib/puppet/provider/gnupg_key/PaxHeader/gnupg.rb", "golja-gnupg-1.2.2/lib/facter/PaxHeader/gnupg_command.rb", "golja-gnupg-1.2.2/lib/facter/PaxHeader/gnupg_installed.rb", "golja-gnupg-1.2.2/files/PaxHeader/broken.public.key", "golja-gnupg-1.2.2/files/PaxHeader/random.key", "golja-gnupg-1.2.2/files/PaxHeader/random.private.key", "golja-gnupg-1.2.2/files/PaxHeader/random.public.key"]
````

**Comment by n1tr0g** [comment]
Hmmm than this must be a bug in tar. I am using OS X with puppet. My versions

puppet --version
4.2.0

tar --version
bsdtar 2.8.3 - libarchive 2.8.3

Does this happen also on my other modules like influxdb ?

**Comment by rnelson0** [comment]
Are you tarring up the file yourself, using `puppet module build`, or something else? Do you have gnu tar available or just bsd tar?

**Comment by n1tr0g** [comment]
I use puppet module build

**Comment by rnelson0** [comment]
@n1tr0g It looks like it just depends on the tar used to package it whether or not PaxHeaders are included. On the receiving side, I see it because I use r10k and it uses minitar to unpack the archives. See https://github.com/puppetlabs/r10k/issues/558, feature request to have minitar ignore the headers instead of alerting.

**Comment by n1tr0g** [comment]
ok repacked on ubuntu and tested it via r10k. The PaxHeaders warning are gone. tnx again for the patience.
